version: "2"
services:
  magento2:
    hostname: "magento2"
    build:
      context: provision/
      args:
        - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
    ports:
      - 80:80
    # volumes:
    #   - ~/.composer/cache:/root/.composer/cache
    # volumes_from:
    #   - dbdata
    #   - appdata
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./magento:/var/www/magento
      - ./provision/bin/installer:/usr/local/bin/installer
      #- ./provision/etc/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
      #- ./provision/etc/php.ini:/etc/php/7.0/cli/conf.d/zz-magento.ini
    depends_on:
      - mysql
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_BASE_URL=${MAGENTO_BASE_URL}
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=admin@123
      - M2SETUP_VERSION=2.2.2

  # appdata:
  #   image: tianon/true
  #   volumes:
  #     - ./magento:/var/www/magento

  # dbdata:
  #   image: tianon/true
  #   volumes:
  #     - ./mysql:/var/lib/mysql


  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root