version: "2"
services:
  magento2:
    hostname: "magento2"
    build:
      context: provision/
      args:
        - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
    ports:
      - 80:80
      - 443:443
      - 3306:3306
    volumes:
      - ~/.composer/cache:/root/.composer/cache
    volumes_from:
      - dbdata
      - appdata
    env_file:
      - ./global.env
      - ./composer.env
    environment:
      - MAGENTO_BASE_URL=${MAGENTO_BASE_URL}
      - M2SETUP_INSTALL_DB=true
      - M2SETUP_BASE_URL=${MAGENTO_BASE_URL}
      - M2SETUP_BACKEND_FRONTNAME=admin
      - M2SETUP_ADMIN_FIRSTNAME=Admin
      - M2SETUP_ADMIN_LASTNAME=User
      - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
      - M2SETUP_ADMIN_USER=admin
      - M2SETUP_ADMIN_PASSWORD=admin@123
      - M2SETUP_VERSION=2.2.2
      # - M2SETUP_USE_SAMPLE_DATA=true
      - MYSQL_ROOT_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2

  appdata:
    image: tianon/true
    volumes:
      - ./magento:/var/www/magento

  dbdata:
    image: tianon/true
    volumes:
      - ./mysql:/var/lib/mysql
